// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmc6DVkefXZ46SMpeKJqs7R11B_KsY-VY',
    appId: '1:50100896020:android:70118b3e85c139032c8201',
    messagingSenderId: '50100896020',
    projectId: 'app-lello-sindico',
    storageBucket: 'app-lello-sindico.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjmE-e5zETfM26QgO5TIJ9Kh1Ih96-ec',
    appId: '1:50100896020:ios:9230ff043b4b9a1e2c8201',
    messagingSenderId: '50100896020',
    projectId: 'app-lello-sindico',
    storageBucket: 'app-lello-sindico.firebasestorage.app',
    androidClientId: '50100896020-58g0l5a6fkqv5rojksi50nsfa04itsnb.apps.googleusercontent.com',
    iosClientId: '50100896020-m6n9j4pct4eqkr4h086j46cck4btl5h6.apps.googleusercontent.com',
    iosBundleId: 'app.lello.sindico',
  );
}
