import 'package:chopper/src/response.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:lello/core/dependency/application_container.dart';
import 'package:lello/environment/environment.dev.dart';
import 'package:lello/lello_app.dart';
import 'package:shared_features/feature/authentication/data/data_source/remote/authentication_api.dart';
import 'package:shared_features/feature/authentication/data/model/access_token_request_model.dart';

void main() async {
  await ApplicationContainer.instance().setUp(DevelopmentEnvironment());
//	ApplicationContainer.instance().locator
  runApp(LelloApp());
}

class AuthApiMock extends AuthenticationApi {
  @override
  Future<Response> post(AccessTokenRequestModel model) async => _mockResponse(
      "{\"access_token\": \"eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJXX19BM05fYWF1Ylo3dUV1dnJTQmJQc05ROUZEQnI2d1lueC1rUXVJbVFnIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9zZXJpYWxudW1iZXIiOiI5MzYyMzU2OTg4NyIsInVpdCI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SnliMnhsSWpvaWJXOXlZWEl1Wm5Wc2JDSXNJbWxrVlhOMVlYSnBieUk2SWpFeU9UUXpJaXdpYVdSUWNtOXFaWFJ2SWpveExDSm1jbTl0SWpvaU1qQXlNUzB3TnkweE0xUXhOVG8xT0Rvd09TNHdOelF6TURnaUxDSjFiblJwYkNJNklqSXdNakV0TURjdE1UTlVNVFk2TlRnNk1Ea3VNRGMwTXpRMklpd2laR0ZrYjNOVmMzVmhjbWx2Y3lJNmV5SnBaQ0k2TVRJNU5ETXNJbVZ0WVdsc0lqb2lkbTFoY21saGJtOUFZWEppYVhRdVkyOXRMbUp5SWl3aWNtVm1aWEpsYm1OcFlYTWlPbHMyTnpNME5ESXNOamN6TkRRM0xEWTJNREV6TXl3M01UWXhORFlzTVRnMU9Ua3hMRGN4TmpFMU5pdzJOek0wTXprc05qY3pORFF6TERZM016UTFOQ3cyTnpNME5EVXNOamN6TkRReExEWTNNelF6TXl3ME5EUXpOallzTmpjek5EUTJMRFkzTWpVd055dzJOek0wTlRNc05qY3pORFF3TERZM016UXpPQ3d6TVRFNE5EQXNOall3TVRJMUxEWTJNREV6TkN3Mk56TTBOVEFzTmpjek5EUTVMRFU1TURBM01DdzJOekkwT1RZc05qY3pORE14TERJMk5ERXdNQ3d5TURFd05EY3NOall3TVRJekxEWTNNelF6Tnl3MU5qWTJOakVzTkRrMk5Ea3hMRFkyTURFeU9DdzJOek0wTkRRc05qY3pORE0xTERZM01qUTVPQ3cyTmpBeE1qWXNNekV4TmpVd0xEWTNNelEwT0N3Mk56TTBNellzTmpjek5EVXhMRFkzTXpRMU1pdzJOakF4TXpVc056RTJNVFExTERVNU1EQTNOQ3cyTnpJME9UY3NOall3TVRNeUxEWTNNelF6TkN3ek1URTROREZkTENKamNHWWlPaUk1TXpZeU16VTJPVGc0TnlJc0ltNXZiV1VpT2lKS1QxTkZJRXBQUVU4Z1FVUkJUVThpTENKMFpXeGxabTl1WlNJNklqRXhPVGcwTVRRNE9UTTBJaXdpYVdSVmMzVmhjbWx2SWpvaU1USTVORE1pZlN3aWFXUkRiMjUwWlhoMGJ5STZORGsyTkRreGZRLjVWX0MySl9Ta3FnN0pGQVY4ZXZieXZmSmVuaUVmc2ZSdGVVa3pCSzU2eEEiLCJ1aXJ0IjoiIiwidWlpZCI6IjEyOTQzIiwicm9sZSI6IlVTRVIiLCJleHAiOjE2MzM1NDY4NDYsImlzcyI6IkxlbGxvQXBpIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxLyJ9.3XO9CVlyA-yRLvF-ogwSepdU0PKelHof3yh-Bzdlrok\",\"refresh_token\": \"\",\"expires_in\": 1585777523834 }");

  @override
  Type get definitionType => AuthenticationApi;

  @override
  Future<Response> switchRoles(String ref) async => _mockResponse(
      "{\"access_token\": \"eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJnZWpMLUFlSUhKTUpjazRpNjZHYXZzTXpjX0NfUmNmNDdEUFZRNG1FTzM4IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9zZXJpYWxudW1iZXIiOiI5MzYyMzU2OTg4NyIsInVpdCI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SnliMnhsSWpvaWJXOXlZWEl1Wm5Wc2JDSXNJbWxrVlhOMVlYSnBieUk2SWpFeU9UUXpJaXdpYVdSUWNtOXFaWFJ2SWpveExDSm1jbTl0SWpvaU1qQXlNUzB3TnkweE0xUXhOVG8xT0Rvd09TNHdOelF6TURnaUxDSjFiblJwYkNJNklqSXdNakV0TURjdE1UTlVNVFk2TlRnNk1Ea3VNRGMwTXpRMklpd2laR0ZrYjNOVmMzVmhjbWx2Y3lJNmV5SnBaQ0k2TVRJNU5ETXNJbVZ0WVdsc0lqb2lkbTFoY21saGJtOUFZWEppYVhRdVkyOXRMbUp5SWl3aWNtVm1aWEpsYm1OcFlYTWlPbHMyTnpNME5ESXNOamN6TkRRM0xEWTJNREV6TXl3M01UWXhORFlzTVRnMU9Ua3hMRGN4TmpFMU5pdzJOek0wTXprc05qY3pORFF6TERZM016UTFOQ3cyTnpNME5EVXNOamN6TkRReExEWTNNelF6TXl3ME5EUXpOallzTmpjek5EUTJMRFkzTWpVd055dzJOek0wTlRNc05qY3pORFF3TERZM016UXpPQ3d6TVRFNE5EQXNOall3TVRJMUxEWTJNREV6TkN3Mk56TTBOVEFzTmpjek5EUTVMRFU1TURBM01DdzJOekkwT1RZc05qY3pORE14TERJMk5ERXdNQ3d5TURFd05EY3NOall3TVRJekxEWTNNelF6Tnl3MU5qWTJOakVzTkRrMk5Ea3hMRFkyTURFeU9DdzJOek0wTkRRc05qY3pORE0xTERZM01qUTVPQ3cyTmpBeE1qWXNNekV4TmpVd0xEWTNNelEwT0N3Mk56TTBNellzTmpjek5EVXhMRFkzTXpRMU1pdzJOakF4TXpVc056RTJNVFExTERVNU1EQTNOQ3cyTnpJME9UY3NOall3TVRNeUxEWTNNelF6TkN3ek1URTROREZkTENKamNHWWlPaUk1TXpZeU16VTJPVGc0TnlJc0ltNXZiV1VpT2lKS1QxTkZJRXBQUVU4Z1FVUkJUVThpTENKMFpXeGxabTl1WlNJNklqRXhPVGcwTVRRNE9UTTBJaXdpYVdSVmMzVmhjbWx2SWpvaU1USTVORE1pZlN3aWFXUkRiMjUwWlhoMGJ5STZORGsyTkRreGZRLjVWX0MySl9Ta3FnN0pGQVY4ZXZieXZmSmVuaUVmc2ZSdGVVa3pCSzU2eEEiLCJ1aXJ0IjoiIiwidWlpZCI6IjEyOTQzIiwicm9sZSI6IlVTRVIiLCJleHAiOjE2MzM1NDY4NzUsImlzcyI6IkxlbGxvQXBpIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxLyJ9.6A0KV1HVXWperHLhjFi9lb7Dirvs8XUAW0YeLfSmJJc\",\"refresh_token\": \"\",\"expires_in\": 1585777523834 }");

  @override
  Future<Response> postInvite(AccessTokenRequestModel model) {
    // TODO: implement postInvite
    throw UnimplementedError();
  }

  @override
  Future<Response> deleteAccount() {
    // TODO: implement deleteAccount
    throw UnimplementedError();
  }
}

Response _mockResponse(String body) {
  return Response(http.BaseResponse as http.BaseResponse, body);
}
