// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsHubert.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsHubertHubert {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptionsHubert have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHubert have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHubert have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHubert have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsHubert are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsNi0sgBBTTE7RTvh4BHjMRse9cU1E34',
    appId: '1:1079065027763:android:e74deb59fccd4f312c7cc6',
    messagingSenderId: '1079065027763',
    projectId: 'app-lello-morar',
    storageBucket: 'app-lello-morar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMjCF4pM8jUcg8hT2uunDlIIvS0je1KoU',
    appId: '1:1079065027763:ios:bbfc2c81123af9512c7cc6',
    messagingSenderId: '1079065027763',
    projectId: 'app-lello-morar',
    storageBucket: 'app-lello-morar.firebasestorage.app',
    androidClientId:
        '1079065027763-bj59bgd3f8j1lcr5md4jvu8dcqcvhrv1.apps.googleusercontent.com',
    iosBundleId: 'app.hubert.morador',
  );
}
