// Gerado a partir dos registros explícitos de `ApplicationContainer`:
// resolve cada tipo para garantir que o grafo de dependências está completo.
// O `CircuitBreakerController` fica de fora porque abre um stream real do
// Firestore ao ser construído.
import 'dart:io';

import 'package:colaborador/core/database/authentication_tablet_database/condominium_info/condominium_info_dao.dart';
import 'package:colaborador/core/database/authentication_tablet_database/employee_info/employee_info_dao.dart';
import 'package:colaborador/core/database/digital_point_database/digital_point/digital_point_dao.dart';
import 'package:colaborador/core/database/digital_point_database/digital_point_log/digital_point_log_dao.dart';
import 'package:colaborador/core/database/lello_database/condominium/condominium_dao.dart';
import 'package:colaborador/core/database/lello_database/condominium_employee_schedule/condominium_employee_schedule_dao.dart';
import 'package:colaborador/core/database/lello_database/employee/employee_dao.dart';
import 'package:colaborador/core/database/lello_database/me/me_dao.dart';
import 'package:colaborador/core/messaging/use_case/ghost_notification_usecase.dart';
import 'package:colaborador/core/uploader/uploader.dart';
import 'package:colaborador/feature/authentication_tablet/data/data_source/local/authentication_tablet_local_data_source.dart';
import 'package:colaborador/feature/authentication_tablet/data/data_source/remote/authentication_tablet_api.dart';
import 'package:colaborador/feature/authentication_tablet/data/data_source/remote/authentication_tablet_remote_data_source.dart';
import 'package:colaborador/feature/authentication_tablet/domain/repository/authentication_tablet_repository.dart';
import 'package:colaborador/feature/authentication_tablet/domain/use_case/get_info_by_condo_code/get_info_by_condo_code.dart';
import 'package:colaborador/feature/authentication_tablet/presentation/bloc/authentication_tablet_bloc.dart';
import 'package:colaborador/feature/digital_point/data/data_source/local/digital_point_local_data_source.dart';
import 'package:colaborador/feature/digital_point/data/data_source/remote/digital_point_api.dart';
import 'package:colaborador/feature/digital_point/data/data_source/remote/digital_point_remote_data_source.dart';
import 'package:colaborador/feature/digital_point/domain/repository/digital_point_repository.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/check_digital_point/check_digital_point.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/register_point/register_point.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/request_digital_point/request_usecase.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/save_point/save_point.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/sync_point_without_login/sync_point_without_login.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/sync_points/sync_points.dart';
import 'package:colaborador/feature/digital_point/domain/use_case/upload_digital_point_to_aws/upload_digital_point_to_aws.dart';
import 'package:colaborador/feature/digital_point/presentation/bloc/digital_point_bloc.dart';
import 'package:colaborador/feature/documents/data/data_source/documents_api.dart';
import 'package:colaborador/feature/documents/data/data_source/documents_remote_data_source.dart';
import 'package:colaborador/feature/documents/domain/repository/documents_repository.dart';
import 'package:colaborador/feature/documents/domain/use_case/get_document_file/get_document_file.dart';
import 'package:colaborador/feature/documents/domain/use_case/get_documents_info_list/get_documents_info_list.dart';
import 'package:colaborador/feature/documents/presentation/benefits/bloc/benefits_bloc.dart';
import 'package:colaborador/feature/documents/presentation/document_file/bloc/document_file_bloc.dart';
import 'package:colaborador/feature/documents/presentation/income_report/bloc/income_report_bloc.dart';
import 'package:colaborador/feature/documents/presentation/pay_stub/bloc/pay_stub_bloc.dart';
import 'package:colaborador/feature/documents/presentation/vacation/bloc/vacation_bloc.dart';
import 'package:colaborador/feature/employee_referral/data/data_source/employee_referral_api.dart';
import 'package:colaborador/feature/employee_referral/data/data_source/employee_referral_remote_data_source.dart';
import 'package:colaborador/feature/employee_referral/domain/repository/employee_referral_repository.dart';
import 'package:colaborador/feature/employee_referral/domain/use_case/get_cities/get_cities_units.dart';
import 'package:colaborador/feature/employee_referral/domain/use_case/register_employee_referral/employee_referral.dart';
import 'package:colaborador/feature/employee_referral/presentation/bloc/employee_referral_bloc.dart';
import 'package:colaborador/feature/home/data/data_source/home_api.dart';
import 'package:colaborador/feature/home/data/data_source/home_remote_data_source.dart';
import 'package:colaborador/feature/home/domain/repository/home_repository.dart';
import 'package:colaborador/feature/home/presentation/bloc/home_bloc.dart';
import 'package:colaborador/feature/home/presentation/widget/home_dialogs/bloc/home_dialogs_bloc.dart';
import 'package:colaborador/feature/home_cards_preferences/bloc/preferences_home_cards_bloc.dart';
import 'package:colaborador/feature/manual_timesheet/data/data_source/remote/manual_timesheet_api.dart';
import 'package:colaborador/feature/manual_timesheet/data/data_source/remote/manual_timesheet_remote_data_source.dart';
import 'package:colaborador/feature/manual_timesheet/domain/repository/manual_timesheet_repository.dart';
import 'package:colaborador/feature/manual_timesheet/domain/use_case/register_manual_timesheet/manual_timesheet.dart';
import 'package:colaborador/feature/manual_timesheet/domain/use_case/upload_sick_note_to_aws/upload_manual_timesheet_to_aws.dart';
import 'package:colaborador/feature/manual_timesheet/presentation/bloc/manual_timesheet_bloc.dart';
import 'package:colaborador/feature/me/data/data_source/local/me_local_data_source.dart';
import 'package:colaborador/feature/me/data/data_source/remote/me_api.dart';
import 'package:colaborador/feature/me/data/data_source/remote/me_remote_data_source.dart';
import 'package:colaborador/feature/me/domain/repository/me_repository.dart';
import 'package:colaborador/feature/me/domain/repository/profile_picture_repository.dart';
import 'package:colaborador/feature/me/domain/use_case/get_me/get_me.dart';
import 'package:colaborador/feature/me/domain/use_case/log_me_out/log_me_out.dart';
import 'package:colaborador/feature/me/domain/use_case/save_me/save_me.dart';
import 'package:colaborador/feature/me/domain/use_case/update_password_me/update_password_me.dart';
import 'package:colaborador/feature/me/domain/use_case/upload_profile_picture/upload_registration_picture.dart';
import 'package:colaborador/feature/me/presentation/bloc/me_bloc.dart';
import 'package:colaborador/feature/preferences/data/data_source/preferences_api.dart';
import 'package:colaborador/feature/preferences/data/data_source/preferences_data_source.dart';
import 'package:colaborador/feature/preferences/domain/repository/preferences_repository.dart';
import 'package:colaborador/feature/preferences/domain/use_case/get_preferences_notification/get_preferences_notification.dart';
import 'package:colaborador/feature/preferences/domain/use_case/put_preferences_notification/put_preferences_notification.dart';
import 'package:colaborador/feature/preferences/presentation/bloc/preferences_notification_bloc.dart';
import 'package:colaborador/feature/proof/data/data_source/remote/proof_api.dart';
import 'package:colaborador/feature/proof/data/data_source/remote/proof_remote_data_source.dart';
import 'package:colaborador/feature/proof/domain/repository/proof_repository.dart';
import 'package:colaborador/feature/proof/domain/use_case/get_proof/get_proof.dart';
import 'package:colaborador/feature/proof/domain/use_case/get_proof_file/get_proof_file.dart';
import 'package:colaborador/feature/proof/presentation/bloc/proof_bloc.dart';
import 'package:colaborador/feature/session/data/data_source/session_local_data_source.dart';
import 'package:colaborador/feature/session/domain/repository/session_repository.dart';
import 'package:colaborador/feature/session/domain/use_case/load_session/load_session.dart';
import 'package:colaborador/feature/session/domain/use_case/save_session/save_session.dart';
import 'package:colaborador/feature/session/presentation/bloc/session_bloc.dart';
import 'package:colaborador/feature/sick_note/data/data_source/remote/sick_note_api.dart';
import 'package:colaborador/feature/sick_note/data/data_source/remote/sick_note_remote_data_source.dart';
import 'package:colaborador/feature/sick_note/domain/repository/sick_note_repository.dart';
import 'package:colaborador/feature/sick_note/domain/use_case/register_sick_note/sick_note.dart';
import 'package:colaborador/feature/sick_note/domain/use_case/upload_sick_note_to_aws/upload_sick_note_to_aws.dart';
import 'package:colaborador/feature/sick_note/presentation/bloc/sick_note_bloc.dart';
import 'package:colaborador/feature/sync_digital_points/presentation/bloc/sync_digital_points_bloc.dart';
import 'package:colaborador/feature/timesheet/data/data_source/remote/timesheet_api.dart';
import 'package:colaborador/feature/timesheet/data/data_source/remote/timesheet_remote_data_source.dart';
import 'package:colaborador/feature/timesheet/domain/repository/timesheet_repository.dart';
import 'package:colaborador/feature/timesheet/domain/use_case/get_timesheet/get_timesheet.dart';
import 'package:colaborador/feature/timesheet/domain/use_case/get_timesheet_detail/get_timesheet_detail.dart';
import 'package:colaborador/feature/timesheet/domain/use_case/get_timesheet_periods/get_timesheet_periods.dart';
import 'package:colaborador/feature/timesheet/domain/use_case/send_email/send_email.dart';
import 'package:colaborador/feature/timesheet/domain/use_case/sign_timesheet/sign_timesheet.dart';
import 'package:colaborador/feature/timesheet/presentation/timesheet_assign_dialog/bloc/timesheet_sign_bloc.dart';
import 'package:colaborador/feature/timesheet/presentation/timesheet_detail_page/bloc/timesheet_detail_bloc.dart';
import 'package:colaborador/feature/timesheet/presentation/timesheet_email_dialog/bloc/timesheet_email_bloc.dart';
import 'package:colaborador/feature/timesheet/presentation/timesheet_page/bloc/timesheet_bloc.dart';
import 'package:essentials/validator/validator.dart';
import 'package:shared_features/feature/authentication/data/data_source/remote/authentication_api.dart';
import 'package:shared_features/feature/code_validation/data/data_source/code_validation_api.dart';
import 'package:shared_features/feature/comfort/data/data_source/comfort_api.dart';
import 'package:shared_features/feature/comfort/data/data_source/comfort_remote_data_source.dart';
import 'package:shared_features/feature/comfort/domain/repository/comfort_repository.dart';
import 'package:shared_features/feature/comfort/domain/use_case/cancel_request/cancel_request.dart';
import 'package:shared_features/feature/comfort/domain/use_case/change_partner_favorite_status/change_partner_favorite_status.dart';
import 'package:shared_features/feature/comfort/domain/use_case/create_coupon_request/create_coupon_request.dart';
import 'package:shared_features/feature/comfort/domain/use_case/find_request_purchase/find_request_purchase.dart';
import 'package:shared_features/feature/comfort/domain/use_case/get_all_partner_reviews/get_all_partner_reviews.dart';
import 'package:shared_features/feature/comfort/domain/use_case/get_all_partners/get_all_partners.dart';
import 'package:shared_features/feature/comfort/domain/use_case/get_my_requests/get_my_requests.dart';
import 'package:shared_features/feature/comfort/domain/use_case/get_partner_coupons/get_partner_coupons.dart';
import 'package:shared_features/feature/comfort/domain/use_case/get_partner_is_favorite/get_partner_is_favorite.dart';
import 'package:shared_features/feature/comfort/domain/use_case/resend_request/resend_request.dart';
import 'package:shared_features/feature/comfort/domain/use_case/send_review_request/send_review_request.dart';
import 'package:shared_features/feature/comfort/domain/use_case/update_request/update_request.dart';
import 'package:shared_features/feature/comfort/presentation/comfort_my_request_item_actions/bloc/comfort_my_request_item_actions_bloc.dart';
import 'package:shared_features/feature/comfort/presentation/comfort_my_request_item_actions/controller/comfort_my_request_item_actions_controller.dart';
import 'package:shared_features/feature/comfort/presentation/comfort_my_requests/bloc/comfort_my_requests_bloc.dart';
import 'package:shared_features/feature/comfort/presentation/comfort_partner_reviews/bloc/comfort_partner_reviews_bloc.dart';
import 'package:shared_features/feature/comfort/presentation/comfort_partners/bloc/comfort_partner_coupons_bloc.dart';
import 'package:shared_features/feature/comfort/presentation/comfort_partners/bloc/comfort_partners_bloc.dart';
import 'package:shared_features/feature/gdp/data/data_source/remote/employee_api.dart';
import 'package:shared_features/feature/gdp/data/data_source/remote/employee_remote_data_source.dart';
import 'package:shared_features/feature/gdp/domain/repository/employee_repository.dart';
import 'package:shared_features/feature/gdp/domain/use_case/get_employee/get_employee.dart';
import 'package:shared_features/feature/gdp/domain/use_case/list_employee/list_employee.dart';
import 'package:shared_features/feature/gdp/employee/presentation/bloc/employee/employee_bloc.dart';
import 'package:shared_features/feature/gdp/employee/presentation/bloc/list/employee_list_bloc.dart';
import 'package:shared_features/feature/gdp/payroll/data/data_source/payroll/payroll_api.dart';
import 'package:shared_features/feature/gdp/payroll/data/data_source/payroll/payroll_remote_data_source.dart';
import 'package:shared_features/feature/gdp/payroll/data/data_source/payroll_entry/payroll_entry_api.dart';
import 'package:shared_features/feature/gdp/payroll/data/data_source/payroll_entry/payroll_entry_remote_data_source.dart';
import 'package:shared_features/feature/gdp/payroll/domain/repository/payroll_entry_repository.dart';
import 'package:shared_features/feature/gdp/payroll/domain/repository/payroll_repository.dart';
import 'package:shared_features/feature/gdp/payroll/domain/use_case/get_payroll/get_payroll.dart';
import 'package:shared_features/feature/gdp/payroll/domain/use_case/list_payroll/list_payroll.dart';
import 'package:shared_features/feature/gdp/payroll/domain/use_case/list_payroll_entry/list_payroll_entry.dart';
import 'package:shared_features/feature/gdp/payroll/presentation/bloc/payroll/payroll_bloc.dart';
import 'package:shared_features/feature/gdp/payroll/presentation/bloc/payroll_entry/payroll_entry_bloc.dart';
import 'package:shared_features/feature/gdp/payslip/data/data_source/payslip_api.dart';
import 'package:shared_features/feature/gdp/payslip/data/data_source/payslip_remote_data_source.dart';
import 'package:shared_features/feature/gdp/payslip/domain/repository/payslip_repository.dart';
import 'package:shared_features/feature/gdp/payslip/domain/use_case/get_payslips/get_payslip.dart';
import 'package:shared_features/feature/gdp/payslip/domain/use_case/get_payslips_file/get_payslip_file.dart';
import 'package:shared_features/feature/gdp/payslip/presentation/bloc/employees/payslip_employees_bloc.dart';
import 'package:shared_features/feature/gdp/payslip/presentation/bloc/selection/payslip_selection_bloc.dart';
import 'package:shared_features/feature/gdp/quick_fix/data/data_source/remote/employee_report_api.dart';
import 'package:shared_features/feature/gdp/quick_fix/data/data_source/remote/employee_report_remote_data_source.dart';
import 'package:shared_features/feature/gdp/quick_fix/domain/repository/employee_report_repository.dart';
import 'package:shared_features/feature/gdp/quick_fix/domain/use_case/get_report/get_employee_report.dart';
import 'package:shared_features/feature/gdp/quick_fix/presentation/bloc/quick_fix/quick_fix_bloc.dart';
import 'package:shared_features/feature/gdp/quick_fix/presentation/bloc/report/quick_fix_report_bloc.dart';
import 'package:shared_features/feature/gdp/timesheet/data/data_source/timesheet_api.dart';
import 'package:shared_features/feature/gdp/timesheet/data/data_source/timesheet_remote_data_source.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/repository/timesheet_repository.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/get_report_day/get_report_day.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/insert_timesheet_event/insert_timesheet_event.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/list_signature/list_signature.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/list_timesheet/list_timesheet.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/list_timesheet_employee/list_timesheet_employee.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/request_timesheet/request_timesheet.dart';
import 'package:shared_features/feature/gdp/timesheet/domain/use_case/sign_timesheet/sign_timesheet.dart';
import 'package:shared_features/feature/gdp/timesheet/presentation/bloc/timesheet_list/timesheet_list_bloc.dart';
import 'package:shared_features/feature/gdp/timesheet/presentation/bloc/timesheet_menu/timesheet_menu_bloc.dart';
import 'package:shared_features/feature/gdp/timesheet/presentation/bloc/timesheet_signatures/timesheet_signatures_bloc.dart';
import 'package:shared_features/feature/gdp/vacation/data/data_source/vacation_api.dart';
import 'package:shared_features/feature/gdp/vacation/data/data_source/vacation_remote_data_source.dart';
import 'package:shared_features/feature/gdp/vacation/domain/repository/vacation_repository.dart';
import 'package:shared_features/feature/gdp/vacation/domain/use_case/get_vacation/get_vacation.dart';
import 'package:shared_features/feature/gdp/vacation/domain/use_case/get_vacation_locked_days/get_vacation_locked_days.dart';
import 'package:shared_features/feature/gdp/vacation/domain/use_case/get_vacation_period/get_vacation_period.dart';
import 'package:shared_features/feature/gdp/vacation/domain/use_case/schedule_vacation/schedule_vacation.dart';
import 'package:shared_features/feature/gdp/vacation/presentation/bloc/details/vacation_bloc.dart';
import 'package:shared_features/feature/gdp/vacation/presentation/bloc/employees/vacation_employees_bloc.dart';
import 'package:shared_features/feature/gdp/vacation/presentation/bloc/schedule_vacation/schedule_vacation_bloc.dart';
import 'package:shared_features/feature/ghost_notification/data/data_source/ghost_notification_api.dart';
import 'package:shared_features/feature/notifications/data/data_source/notifications_api.dart';
import 'package:shared_features/feature/registration/data/data_source/registration_api.dart';
import 'package:shared_features/feature/reset_password/data/data_source/password_reset_api.dart';
import 'package:colaborador/core/dependency/application_container.dart';
import 'package:essentials/essentials.dart' hide isNotNull;
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_features/shared_features.dart';

import '../../helpers/fake_permission_handler.dart';
import '../../helpers/firebase_mocks.dart';
import '../../helpers/init_sqflite_ffi.dart';
import '../../helpers/test_application_container.dart' show TestEnvironment;

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();
  initSqfliteForTests();

  late ApplicationContainer container;

  setUp(() async {
    FlavorConfig.init();
    setFakePermissionHandler(FakePermissionHandler());
    await setUpFakeFirebase();
    SharedPreferences.setMockInitialValues({});
    Hive.init(Directory.systemTemp.createTempSync('colaborador_di_all').path);
    await ApplicationContainer.instance().locator.reset(dispose: true);
    container = ApplicationContainer.instance();
    await container.setUp(TestEnvironment());
  });

  tearDown(() => ApplicationContainer.instance().locator.reset(dispose: true));

  test('resolve as dependências registradas (1)', () {
    expect(container.resolve<AccessTokenLocalDataSource>(), isNotNull);
    expect(container.resolve<AccessTokenRemoteDataSource>(), isNotNull);
    expect(container.resolve<AccessTokenRepository>(), isNotNull);
    expect(container.resolve<Authenticate>(), isNotNull);
    expect(container.resolve<AuthenticateFirebase>(), isNotNull);
    expect(container.resolve<AuthenticationApi>(), isNotNull);
    expect(container.resolve<AuthenticationBloc>(), isNotNull);
    expect(container.resolve<AuthenticationTabletApi>(), isNotNull);
    expect(container.resolve<AuthenticationTabletBloc>(), isNotNull);
    expect(container.resolve<AuthenticationTabletLocalDataSource>(), isNotNull);
    expect(
        container.resolve<AuthenticationTabletRemoteDataSource>(), isNotNull);
    expect(container.resolve<AuthenticationTabletRepository>(), isNotNull);
    expect(container.resolve<AwsUploadFileUsecase>(), isNotNull);
    expect(container.resolve<BenefitsBloc>(), isNotNull);
    expect(container.resolve<CancelRequestUseCase>(), isNotNull);
    expect(container.resolve<ChangePartnerFavoriteStatusUseCase>(), isNotNull);
    expect(container.resolve<CheckDigitalPointUsecase>(), isNotNull);
    expect(container.resolve<ClearData>(), isNotNull);
    expect(container.resolve<CodeValidationApi>(), isNotNull);
    expect(container.resolve<CodeValidationRemoteDataSource>(), isNotNull);
    expect(container.resolve<CodeValidationRepository>(), isNotNull);
    expect(container.resolve<ComfortApi>(), isNotNull);
    expect(container.resolve<ComfortMyRequestItemActionsBloc>(), isNotNull);
    expect(
        container.resolve<ComfortMyRequestItemActionsController>(), isNotNull);
    expect(container.resolve<ComfortMyRequestsBloc>(), isNotNull);
    expect(container.resolve<ComfortPartnerCouponsBloc>(), isNotNull);
    expect(container.resolve<ComfortPartnerReviewsBloc>(), isNotNull);
    expect(container.resolve<ComfortPartnersBloc>(), isNotNull);
    expect(container.resolve<ComfortRemoteDataSource>(), isNotNull);
    expect(container.resolve<ComfortRepository>(), isNotNull);
  });

  test('resolve as dependências registradas (2)', () {
    expect(container.resolve<CondominiumDao>(), isNotNull);
    expect(container.resolve<CondominiumEmployeeScheduleDao>(), isNotNull);
    expect(container.resolve<CondominiumInfoDao>(), isNotNull);
    expect(container.resolve<CreateCouponRequestUseCase>(), isNotNull);
    expect(container.resolve<DeleteAccount>(), isNotNull);
    expect(container.resolve<DeleteAllReadNotification>(), isNotNull);
    expect(container.resolve<DeleteNotification>(), isNotNull);
    expect(container.resolve<DigitalPointApi>(), isNotNull);
    expect(container.resolve<DigitalPointBloc>(), isNotNull);
    expect(container.resolve<DigitalPointDao>(), isNotNull);
    expect(container.resolve<DigitalPointLocalDataSource>(), isNotNull);
    expect(container.resolve<DigitalPointLogDao>(), isNotNull);
    expect(container.resolve<DigitalPointRemoteDataSource>(), isNotNull);
    expect(container.resolve<DigitalPointRepository>(), isNotNull);
    expect(container.resolve<DisableFcm>(), isNotNull);
    expect(container.resolve<DocumentFileBloc>(), isNotNull);
    expect(container.resolve<DocumentsApi>(), isNotNull);
    expect(container.resolve<DocumentsRemoteDataSource>(), isNotNull);
    expect(container.resolve<DocumentsRepository>(), isNotNull);
    expect(container.resolve<EmployeeApi>(), isNotNull);
    expect(container.resolve<EmployeeBloc>(), isNotNull);
    expect(container.resolve<EmployeeDao>(), isNotNull);
    expect(container.resolve<EmployeeInfoDao>(), isNotNull);
    expect(container.resolve<EmployeeListBloc>(), isNotNull);
    expect(container.resolve<EmployeeReferralApi>(), isNotNull);
    expect(container.resolve<EmployeeReferralBloc>(), isNotNull);
    expect(container.resolve<EmployeeReferralRemoteDataSource>(), isNotNull);
    expect(container.resolve<EmployeeReferralRepository>(), isNotNull);
    expect(container.resolve<EmployeeRemoteDataSource>(), isNotNull);
    expect(container.resolve<EmployeeReportApi>(), isNotNull);
  });

  test('resolve as dependências registradas (3)', () {
    expect(container.resolve<EmployeeReportRemoteDataSource>(), isNotNull);
    expect(container.resolve<EmployeeReportRepository>(), isNotNull);
    expect(container.resolve<EmployeeRepository>(), isNotNull);
    expect(container.resolve<ExpiredSessionLocalDataSource>(), isNotNull);
    expect(container.resolve<ExpiredSessionRepository>(), isNotNull);
    expect(container.resolve<FindRequestPurchaseUseCase>(), isNotNull);
    expect(container.resolve<GetAllPartnerReviewsUseCase>(), isNotNull);
    expect(container.resolve<GetAllPartnersUseCase>(), isNotNull);
    expect(container.resolve<GetCitiesUsecase>(), isNotNull);
    expect(container.resolve<GetDados2fa>(), isNotNull);
    expect(container.resolve<GetDocumentFileUseCase>(), isNotNull);
    expect(container.resolve<GetDocumentsInfoListUseCase>(), isNotNull);
    expect(container.resolve<GetEmployee>(), isNotNull);
    expect(container.resolve<GetEmployeeReport>(), isNotNull);
    expect(container.resolve<GetInfoByCondoCodeUseCase>(), isNotNull);
    expect(container.resolve<GetLockedDays>(), isNotNull);
    expect(container.resolve<GetMe>(), isNotNull);
    expect(container.resolve<GetMyRequestsUseCase>(), isNotNull);
    expect(container.resolve<GetMyUser>(), isNotNull);
    expect(container.resolve<GetNotificationUseCase>(), isNotNull);
    expect(container.resolve<GetNotifications>(), isNotNull);
    expect(container.resolve<GetPartnerCouponsUseCase>(), isNotNull);
    expect(container.resolve<GetPartnerIsFavoriteUseCase>(), isNotNull);
    expect(container.resolve<GetPayroll>(), isNotNull);
    expect(container.resolve<GetPayslip>(), isNotNull);
    expect(container.resolve<GetPayslipFile>(), isNotNull);
    expect(container.resolve<GetProofFileUseCase>(), isNotNull);
    expect(container.resolve<GetProofUseCase>(), isNotNull);
    expect(container.resolve<GetReportDay>(), isNotNull);
    expect(container.resolve<GetTimesheetDetailUsecase>(), isNotNull);
  });

  test('resolve as dependências registradas (4)', () {
    expect(container.resolve<GetTimesheetPeriodsUsecase>(), isNotNull);
    expect(container.resolve<GetTimesheetUsecase>(), isNotNull);
    expect(container.resolve<GetToken>(), isNotNull);
    expect(container.resolve<GetVacation>(), isNotNull);
    expect(container.resolve<GetVacationPeriod>(), isNotNull);
    expect(container.resolve<GhostNotificationApi>(), isNotNull);
    expect(container.resolve<GhostNotificationDatasource>(), isNotNull);
    expect(container.resolve<GhostNotificationRepository>(), isNotNull);
    expect(container.resolve<GhostNotificationUsecase>(), isNotNull);
    expect(container.resolve<HomeApi>(), isNotNull);
    expect(container.resolve<HomeBloc>(), isNotNull);
    expect(container.resolve<HomeDialogBloc>(), isNotNull);
    expect(container.resolve<HomeRemoteDataSource>(), isNotNull);
    expect(container.resolve<HomeRepository>(), isNotNull);
    expect(container.resolve<IncomeReportBloc>(), isNotNull);
    expect(container.resolve<InsertTimesheetEvent>(), isNotNull);
    expect(container.resolve<ListEmployee>(), isNotNull);
    expect(container.resolve<ListPayroll>(), isNotNull);
    expect(container.resolve<ListPayrollEntry>(), isNotNull);
    expect(container.resolve<ListSignature>(), isNotNull);
    expect(container.resolve<ListTimesheet>(), isNotNull);
    expect(container.resolve<ListTimesheetEmployee>(), isNotNull);
    expect(container.resolve<LoadSession>(), isNotNull);
    expect(container.resolve<LogMeOut>(), isNotNull);
    expect(container.resolve<Logout>(), isNotNull);
    expect(container.resolve<ManualTimeSheetApi>(), isNotNull);
    expect(container.resolve<ManualTimeSheetBloc>(), isNotNull);
    expect(container.resolve<ManualTimeSheetRemoteDataSource>(), isNotNull);
    expect(container.resolve<ManualTimeSheetRepository>(), isNotNull);
    expect(container.resolve<MarkAllReadNotification>(), isNotNull);
  });

  test('resolve as dependências registradas (5)', () {
    expect(container.resolve<MeApi>(), isNotNull);
    expect(container.resolve<MeBloc>(), isNotNull);
    expect(container.resolve<MeDao>(), isNotNull);
    expect(container.resolve<MeLocalDataSource>(), isNotNull);
    expect(container.resolve<MeRemoteDataSource>(), isNotNull);
    expect(container.resolve<MeRepository>(), isNotNull);
    expect(container.resolve<NotificationResume>(), isNotNull);
    expect(container.resolve<NotificationsApi>(), isNotNull);
    expect(container.resolve<NotificationsRemoteDataSource>(), isNotNull);
    expect(container.resolve<NotificationsRepository>(), isNotNull);
    expect(container.resolve<PasswordResetApi>(), isNotNull);
    expect(container.resolve<PasswordResetRemoteDataSource>(), isNotNull);
    expect(container.resolve<PasswordResetRepository>(), isNotNull);
    expect(container.resolve<PayStubBloc>(), isNotNull);
    expect(container.resolve<PayrollApi>(), isNotNull);
    expect(container.resolve<PayrollBloc>(), isNotNull);
    expect(container.resolve<PayrollEntryApi>(), isNotNull);
    expect(container.resolve<PayrollEntryBloc>(), isNotNull);
    expect(container.resolve<PayrollEntryRemoteDataSource>(), isNotNull);
    expect(container.resolve<PayrollEntryRepository>(), isNotNull);
    expect(container.resolve<PayrollRemoteDataSource>(), isNotNull);
    expect(container.resolve<PayrollRepository>(), isNotNull);
    expect(container.resolve<PayslipApi>(), isNotNull);
    expect(container.resolve<PayslipEmployeesBloc>(), isNotNull);
    expect(container.resolve<PayslipRemoteDataSource>(), isNotNull);
    expect(container.resolve<PayslipRepository>(), isNotNull);
    expect(container.resolve<PayslipSelectionBloc>(), isNotNull);
    expect(container.resolve<PreferencesApi>(), isNotNull);
    expect(container.resolve<PreferencesDataSource>(), isNotNull);
    expect(container.resolve<PreferencesHomeCardsBloc>(), isNotNull);
  });

  test('resolve as dependências registradas (6)', () {
    expect(container.resolve<PreferencesNotificationBloc>(), isNotNull);
    expect(container.resolve<PreferencesRepository>(), isNotNull);
    expect(container.resolve<ProfilePictureRepository>(), isNotNull);
    expect(container.resolve<ProofApi>(), isNotNull);
    expect(container.resolve<ProofBloc>(), isNotNull);
    expect(container.resolve<ProofRemoteDataSource>(), isNotNull);
    expect(container.resolve<ProofRepository>(), isNotNull);
    expect(container.resolve<PutNotificationUseCase>(), isNotNull);
    expect(container.resolve<QuickFixBloc>(), isNotNull);
    expect(container.resolve<QuickFixReportBloc>(), isNotNull);
    expect(container.resolve<ReadNotification>(), isNotNull);
    expect(container.resolve<RefreshToken>(), isNotNull);
    expect(container.resolve<RefreshTokenRemoteDataSource>(), isNotNull);
    expect(container.resolve<RefreshTokenRepository>(), isNotNull);
    expect(container.resolve<Register>(), isNotNull);
    expect(container.resolve<RegisterEmployeeReferralUsecase>(), isNotNull);
    expect(container.resolve<RegisterFcm>(), isNotNull);
    expect(container.resolve<RegisterManualTimeSheetUsecase>(), isNotNull);
    expect(container.resolve<RegisterPointUsecase>(), isNotNull);
    expect(container.resolve<RegisterSickNoteUsecase>(), isNotNull);
    expect(container.resolve<RegistrationApi>(), isNotNull);
    expect(container.resolve<RegistrationRemoteDataSource>(), isNotNull);
    expect(container.resolve<RegistrationRepository>(), isNotNull);
    expect(container.resolve<Request2fa>(), isNotNull);
    expect(container.resolve<RequestDigitalUsecase>(), isNotNull);
    expect(container.resolve<RequestTimesheet>(), isNotNull);
    expect(container.resolve<RequestValidationCode>(), isNotNull);
    expect(container.resolve<ResendRequestUseCase>(), isNotNull);
    expect(container.resolve<ResetPassword>(), isNotNull);
    expect(container.resolve<ResetPassword2fa>(), isNotNull);
  });

  test('resolve as dependências registradas (7)', () {
    expect(container.resolve<ResetPasswordBloc>(), isNotNull);
    expect(container.resolve<SaveMe>(), isNotNull);
    expect(container.resolve<SavePointUsecase>(), isNotNull);
    expect(container.resolve<SaveSession>(), isNotNull);
    expect(container.resolve<ScheduleVacation>(), isNotNull);
    expect(container.resolve<ScheduleVacationBloc>(), isNotNull);
    expect(container.resolve<SendPushCallback>(), isNotNull);
    expect(container.resolve<SendReviewRequestUseCase>(), isNotNull);
    expect(container.resolve<SessionBloc>(), isNotNull);
    expect(container.resolve<SessionLocalDataSource>(), isNotNull);
    expect(container.resolve<SessionRepository>(), isNotNull);
    expect(container.resolve<SickNoteApi>(), isNotNull);
    expect(container.resolve<SickNoteBloc>(), isNotNull);
    expect(container.resolve<SickNoteRemoteDataSource>(), isNotNull);
    expect(container.resolve<SickNoteRepository>(), isNotNull);
    expect(container.resolve<SignTimesheet>(), isNotNull);
    expect(container.resolve<SignTimesheetUsecase>(), isNotNull);
    expect(container.resolve<SwitchRoles>(), isNotNull);
    expect(container.resolve<SyncDigitalPointsBloc>(), isNotNull);
    expect(container.resolve<SyncPointWithoutLoginUsecase>(), isNotNull);
    expect(container.resolve<SyncPointsUsecase>(), isNotNull);
    expect(container.resolve<TimesheetApi>(), isNotNull);
    expect(container.resolve<TimesheetBloc>(), isNotNull);
    expect(container.resolve<TimesheetDetailBloc>(), isNotNull);
    expect(container.resolve<TimesheetEmailBloc>(), isNotNull);
    expect(container.resolve<TimesheetGDPApi>(), isNotNull);
    expect(container.resolve<TimesheetGDPRemoteDataSource>(), isNotNull);
    expect(container.resolve<TimesheetGDPRepository>(), isNotNull);
    expect(container.resolve<TimesheetListBloc>(), isNotNull);
    expect(container.resolve<TimesheetMenuBloc>(), isNotNull);
  });

  test('resolve as dependências registradas (8)', () {
    expect(container.resolve<TimesheetRemoteDataSource>(), isNotNull);
    expect(container.resolve<TimesheetRepository>(), isNotNull);
    expect(container.resolve<TimesheetSendEmailUsecase>(), isNotNull);
    expect(container.resolve<TimesheetSignBloc>(), isNotNull);
    expect(container.resolve<TimesheetSignaturesBloc>(), isNotNull);
    expect(container.resolve<UpdatePasswordMe>(), isNotNull);
    expect(container.resolve<UpdateRequestUseCase>(), isNotNull);
    expect(container.resolve<UploadDigitalPointToAwsUsecase>(), isNotNull);
    expect(container.resolve<UploadManualTimeSheetToAwsUsecase>(), isNotNull);
    expect(container.resolve<UploadProfilePicture>(), isNotNull);
    expect(container.resolve<UploadSickNoteToAwsUsecase>(), isNotNull);
    expect(container.resolve<Uploader>(), isNotNull);
    expect(container.resolve<VacationApi>(), isNotNull);
    expect(container.resolve<VacationBloc>(), isNotNull);
    expect(container.resolve<VacationEmployeesBloc>(), isNotNull);
    expect(container.resolve<VacationGDPBloc>(), isNotNull);
    expect(container.resolve<VacationRemoteDataSource>(), isNotNull);
    expect(container.resolve<VacationRepository>(), isNotNull);
    expect(container.resolve<Validate2fa>(), isNotNull);
    expect(container.resolve<ValidateCode>(), isNotNull);
    expect(container.resolve<Validator>(), isNotNull);
  });
}
