name: sindico_viver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.32.1+561

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lello:
    path: ../app-lello-sindico/
  essentials:
    path: ../app-lello-essentials/
  shared_features:
    path: ../app-lello-shared/
  lib_facedetection:
    path: ../app-lello-shared/packages/lib_facedetection/
  dropdown_button2: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.4
  drift_dev: ^2.9.0
  chopper_generator: ^8.1.0
  dependency_validator: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  json_serializable: ^6.0.0
  mockito: ^5.0.16

dependency_overrides:
  intl: 0.20.2

flutter_app_name:
  name: "App para síndicos"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_carimbeira_sindico.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - lang/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: ../app-lello-sindico/fonts/playfairdisplay.ttf
    - family: Roboto
      fonts:
        - asset: ../app-lello-sindico/fonts/Roboto-Black.ttf
        - asset: ../app-lello-sindico/fonts/Roboto-Bold.ttf
        - asset: ../app-lello-sindico/fonts/Roboto-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
