source "https://rubygems.org"

gem 'fastlane'
gem 'cocoapods', '>= 1.16.2'
gem 'activesupport'
gem 'bundler', '~> 2.7.1'
gem 'google-api-client', '>= 0.37.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
