sonar.projectKey=app-lello-sindico
sonar.projectName=app-lello-sindico
sonar.host.url=http://localhost:9000
sonar.sourceEncoding=UTF-8

sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=test/**/*_test.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**,lib/environment/**
sonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,lib/environment/**
sonar.dart.lcov.reportPaths=coverage/lcov.info
