// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps (Hubert flavor).
///
/// Example:
/// ```dart
/// import 'firebase_options_hubert.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsHubert.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsHubert {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1uwPe6jJa_TPijTllDOTh_bciMrhZXcw',
    appId: '1:567768661045:web:726f5e38e539c41cfe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    authDomain: 'app-lello-colaborador2.firebaseapp.com',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
    measurementId: 'G-D140Z0G94L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qqLHx05mNVeuMmEApxbSHv6nUEZMqsI',
    appId: '1:567768661045:android:396fbe0cdfb8b04dfe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-cgi-SG2J4sobvbRTTp479CxTiYDwwns',
    appId: '1:567768661045:ios:91e85c69f7723caafe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
    iosBundleId: 'app.hubert.colaborador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-cgi-SG2J4sobvbRTTp479CxTiYDwwns',
    appId: '1:567768661045:ios:0bdddb94c63fd849fe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
    iosClientId:
        '567768661045-0pdusmsqdetkj8bdkljds8au5dh9ur4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appLelloColaborador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuQkwpPiE4Hxm0p1WQoHQTSUr7UxirG18',
    appId: '1:567768661045:web:ac85906a359de8eefe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    authDomain: 'app-lello-colaborador2.firebaseapp.com',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
    measurementId: 'G-EGH7SSHRVH',
  );
}
