// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_lello.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptionsLello.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsLello {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qqLHx05mNVeuMmEApxbSHv6nUEZMqsI',
    appId: '1:567768661045:android:d10eebfc85ad5d23fe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-cgi-SG2J4sobvbRTTp479CxTiYDwwns',
    appId: '1:567768661045:ios:f04f226da0c90aa7fe457c',
    messagingSenderId: '567768661045',
    projectId: 'app-lello-colaborador2',
    storageBucket: 'app-lello-colaborador2.firebasestorage.app',
    iosClientId:
        '567768661045-7lab3osb5lrsch4fuan1j6cee3ln678i.apps.googleusercontent.com',
    iosBundleId: 'app.lello.colaborador',
  );
}
