enum FeaturesRoutesEnum {
  //Acordos
  ACORDO_APROVADO_AUTOMATICAMENTE,
  ACORDO_PAGAMENTO_PARCELA,
  ACORDO_BOLETO_DISPONIVEL,
  ACORDO_PROPOSTA_APROVADA,
  ACORDO_PROPOSTA_ENVIADA,
  ACORDO_PROPOSTA_RECUSADA,
  ACORDO_PARCELA,
  ACORDO_PROPOSTA,
  ACORDOS_COTA_2,
  ACORDOS_COTA_30,
  ACORDOS_COTA_58,

  //Correspondencia
  CORRESPONDENCIAS_ENTRADA,
  CORRESPONDENCIAS_RETIRADA,

  //Controle de acesso
  ENTRADA_AUTORIZACAO_VISITANTE_NOVO,
  ENTRADA_LIBERACAO,

  //Novo usuário acessou o app - morador convidado
  MORADORES_ACESSOU,

  //Notificações não lidas
  NOTIFICACOES_NAO_LIDAS,

  //Ocorrências
  OCORRENCIA_RESPOSTA,
  OCORRENCIA_NOVA,

  //BOLETOS
  BOLETOS,

  //RESERVAS
  RESERVA_MUDANCAS,
  RESERVA_AREA,

  //PPC
  PPC_MES_FECHADO,
  PPC_DISPONIVEL,

  //DOCUMENTOS
  DOCUMENTOS_CIRCULARES,
  DOCUMENTOS_EDITAIS,
  DOCUMENTOS_ATAS,
  DOCUMENTOS_ADVERTENCIAS,
  DOCUMENTOS_MULTAS,

  //Assembleia
  ASSEMBLEIA,

  ESPELHO_PONTO,

  //RESERVAS
  PORTARIA_BLOQUEADA,
  PORTARIA_LIBERADA,

  //Despesas
  DESPESAS_APROVACAO,
  DESPESAS_PAGAMENTO_NOVO,

  //COMODIDADES
  COMODIDADES,
  COMODIDADES_CATEGORIA,
  COMODIDADES_PARCEIRO,

  //GDP
  ALERTA_FALTAS,
  ALERTA_HORAS_EXTRAS,
  ALERTA_HORAS_ATRASO,
  ALERTA_ASSINATURA_SINDICO,
  ALERTA_ASSINATURA_FUNCIONARIO,

  //GESTAO TECNICA OPERACIONAL
  GESTAO_TECNICA,

  //SEGUROS
  SEGUROS,

  //MINHA CONTA
  MINHA_CONTA,

  //TROCA DE TITULARIDADE
  TROCA_TITULARIDADE,

  //BELLA
  BELLA,
}
