// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsNi0sgBBTTE7RTvh4BHjMRse9cU1E34',
    appId: '1:1079065027763:android:15839aa1354ec98f2c7cc6',
    messagingSenderId: '1079065027763',
    projectId: 'app-lello-morar',
    storageBucket: 'app-lello-morar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMjCF4pM8jUcg8hT2uunDlIIvS0je1KoU',
    appId: '1:1079065027763:ios:d5b3ba3e4e24a6482c7cc6',
    messagingSenderId: '1079065027763',
    projectId: 'app-lello-morar',
    storageBucket: 'app-lello-morar.appspot.com',
    androidClientId: '1079065027763-bj59bgd3f8j1lcr5md4jvu8dcqcvhrv1.apps.googleusercontent.com',
    iosClientId: '1079065027763-s63578hc7cgdj32ai44ra9p35p14okup.apps.googleusercontent.com',
    iosBundleId: 'app.lello.lellomorar',
  );
}
