enum BannerFeatureEnum {
  others,
  lelloMorarComfortPartner,
  lelloMorarInsurance,
  lelloMorarTDB,

  // Backend V2 feature values.
  acordos,
  acordosRealizados,
  assembleia,
  autorizacaoEntrada,
  boletos,
  correspondencias,
  despesasAprovacoesPendentes,
  despesasConsultarPagamentos,
  documentosAdvertencias,
  documentosAtas,
  documentosCirculares,
  documentosEditais,
  documentosMultas,
  espelhoPonto,
  minhasOcorrencias,
  moradoresSubmoradores,
  ocorrencias,
  prestacaoContas,
  reservaAreaAgendamentos,
  minhaConta,
  bella,
  seguros,
  gestaoTecnica,
}
